README.md
File example in README looked ugly.
=> Wrap part of README.md in code block

README.md
made an oopsie in my last PR, this fixes it
=> Remove unecessary escape chars

.travis.yml
- No travis yaml
- add travis yaml
=> Add test travis, no tests yet

.gitignore, docs/configs.md, src/main/java/com/bot/Config.java, src/main/java/com/bot/Main.java, src/main/java/com/bot/ShardingManager.java, src/main/java/com/bot/db/DataLoader.java
Config is convoluted and overly complicated
Changing Config.java to only use 1 file, singleton, public static final config vars. Add config.md for documentation.
=> Create configs.md and change Config.java

res/db/sql.migration/V1_Create_Initial_Db.sql, src/main/java/com/bot/Logger.java, src/main/java/com/bot/Main.java, src/main/java/com/bot/ShardingManager.java, src/main/java/com/bot/commands/battleroyale/BattleRoyaleCommand.java, src/main/java/com/bot/db/DataLoader.java, src/main/java/com/bot/db/PlaylistRepository.java, src/main/java/com/bot/db/ReadConnectionPool.java, src/main/java/com/bot/models/AudioTrack.java, src/main/java/com/bot/models/Playlist.java
- TODO: What was the problem?
- TODO: Is this related to any open issues? If so, link them here. If not, put none or remove.
- # TODO: Add any other users you want to help review this pr.
=> Add sql repositories models

src/main/java/com/bot/Config.java
- TODO: What was the problem?
#22 
Default to env vars if no config file
- # TODO: Add any other users you want to help review this pr.
=> Allowed use of env vars

Dockerfile, docker-compose.yml
No support for env variables
#23 #22 both addressed with this, will have follow up with docs
=> Support using Environment variables and update docker

.travis.yml
=> Dockerize travis

src/main/java/com/bot/voice/VoiceSendHandler.java, src/main/test/voice/TestQueuedAudioTrack.java, src/main/test/voice/TestVoiceSendHandler.java
- like not many tests
- make some
=> test edits

pom.xml
- We have no way to see test coverage
- Add Jacoco to handle generating the test coverage
=> Add Jacoco for test coverage

src/main/java/com/bot/ShardingManager.java, src/main/java/com/bot/commands/general/InviteCommand.java, src/main/java/com/bot/commands/voice/ListMyPlaylistCommand.java
- To achieve feature parity we need this command
- Added the new command
- Invite Command
- None
no
no
no
=> Add Invite Command

src/main/java/com/bot/RedditConnection.java, src/main/java/com/bot/db/ChannelRespository.java, src/main/java/com/bot/db/ConnectionPool.java, src/main/java/com/bot/db/DataLoader.java, src/main/java/com/bot/db/PlaylistRepository.java, src/main/java/com/bot/db/ReadConnectionPool.java, src/main/java/com/bot/models/InternalChannel.java, src/main/java/com/bot/models/InternalTextChannel.java, src/main/java/com/bot/models/InternalVoiceChannel.java, src/main/java/com/bot/utils/RedditHelper.java, src/main/resources/db/migration/V1__create_initial_db.sql, src/main/resources/db/migration/V2__add_voice_channel_table.sql
Add a start of a framework to sync metadata (channels, users and guilds from the db)
=> framework for channels to be accessed from the db

src/main/java/com/bot/Bot.java, src/main/java/com/bot/ShardingManager.java, src/main/java/com/bot/commands/settings/DefaultVolumeCommand.java, src/main/java/com/bot/commands/settings/GetSettingsCommand.java, src/main/java/com/bot/commands/settings/SetBaseRoleCommand.java, src/main/java/com/bot/commands/settings/SetModRoleCommand.java, src/main/java/com/bot/commands/settings/SetNSFWCommand.java, src/main/java/com/bot/commands/settings/SetVoiceRoleCommand.java
- No way to manage the settings of a guild
- Add commands to do that
- settings, baserole, nsfwrole, voicerole, modrole
=> Added commands to manage the guild settings

src/main/java/com/bot/commands/voice/PlayCommand.java, src/main/java/com/bot/commands/voice/SearchCommand.java, src/main/java/com/bot/db/ConnectionPool.java, src/main/java/com/bot/db/ReadConnectionPool.java
Add support to add multiple songs from a playlist on yt in the play command. Also mess some more with Hikari to try and fix db issues.
=> Add playlists and db connection fix

src/main/java/com/bot/Bot.java
=> enforce default volime

src/main/java/com/bot/ShardingManager.java, src/main/java/com/bot/commands/reddit/NewPostCommand.java, src/main/java/com/bot/commands/reddit/RandomPostCommand.java, src/main/java/com/bot/commands/reddit/TopPostCommand.java, src/main/java/com/bot/commands/settings/DisableNSFWCommand.java, src/main/java/com/bot/commands/settings/EnableNSFWCommand.java, src/main/java/com/bot/db/ChannelDAO.java, src/main/java/com/bot/utils/CommandPermissions.java, src/main/java/com/bot/utils/RedditHelper.java
No way to set nsfw permissions for channels, no reddit command nsfw checks
Add them and enable reddit commands 
rr, tr, nr, enablensfw, disablensfw
=> enable reddit commands with nsfw checks

pom.xml, src/main/java/com/bot/Bot.java, src/main/java/com/bot/Main.java, src/main/java/com/bot/ShardingManager.java, src/main/java/com/bot/commands/general/PingCommand.java, src/main/java/com/bot/commands/general/ShardStatsCommand.java, src/main/java/com/bot/commands/voice/LoadGuildPlaylistCommand.java, src/main/java/com/bot/commands/voice/LoadMyPlaylistCommand.java, src/main/java/com/bot/commands/voice/StopCommand.java, src/main/java/com/bot/db/ConnectionPool.java, src/main/java/com/bot/db/DataLoader.java, src/main/java/com/bot/db/ReadConnectionPool.java, src/main/java/com/bot/models/InternalShard.java
Shards were handled really primitively. 
Make shards a little more robust and add commands around status checks
- ping
- shardinfo
=> Refactored sharding and added a shardinfo command

pom.xml, src/main/java/com/bot/Bot.java, src/main/java/com/bot/commands/reddit/NewPostCommand.java, src/main/java/com/bot/commands/reddit/RandomPostCommand.java, src/main/java/com/bot/commands/reddit/TopPostCommand.java, src/main/java/com/bot/db/ChannelDAO.java, src/main/java/com/bot/db/ConnectionPool.java, src/main/java/com/bot/db/GuildDAO.java, src/main/java/com/bot/db/MembershipDAO.java, src/main/java/com/bot/db/PlaylistDAO.java, src/main/java/com/bot/db/ReadConnectionPool.java, src/main/java/com/bot/utils/DbHelpers.java, src/main/test/java/db/ChannelIT.java, src/main/test/java/db/GuildIT.java, src/main/test/java/db/PlaylistIT.java
=> Refactor connections in daos

src/main/java/com/bot/commands/general/PingCommand.java, src/main/java/com/bot/commands/general/ShardStatsCommand.java, src/main/java/com/bot/commands/settings/AddPrefixCommand.java, src/main/java/com/bot/commands/settings/PrefixesCommand.java, src/main/java/com/bot/commands/settings/RemovePrefixCommand.java
=> Add perms checks to a couple of forgotton commadns

pom.xml, src/main/java/com/bot/Main.java, src/main/java/com/bot/db/GuildDAO.java, src/main/java/com/bot/db/MembershipDAO.java, src/main/java/com/bot/preferences/GuildPreferencesManager.java
=> Various bug fixes

pom.xml, src/main/java/com/bot/Bot.java, src/main/java/com/bot/ShardingManager.java, src/main/java/com/bot/commands/owner/UpdateGuildCountCommand.java, src/main/java/com/bot/models/InternalShard.java, src/main/java/com/bot/utils/Config.java, src/main/java/com/bot/utils/HttpUtils.java
- With being added to some new bot websites we need to post some stats to them
- Add a static method to post to the sites in an HttpUtils class
yes, bot apis
=> Post statistics

src/main/java/com/bot/Bot.java, src/main/java/com/bot/ShardingManager.java, src/main/java/com/bot/caching/Cache.java, src/main/java/com/bot/caching/CacheObject.java, src/main/java/com/bot/caching/GuildCache.java, src/main/java/com/bot/caching/MarkovModelCache.java, src/main/java/com/bot/commands/meme/CommentCommand.java, src/main/java/com/bot/db/GuildDAO.java, src/main/java/com/bot/models/MarkovModel.java, src/main/java/com/bot/preferences/GuildPreferencesManager.java, src/main/java/com/bot/utils/Config.java, src/main/java/com/bot/utils/MetricsManager.java, src/main/test/java/db/GuildIT.java
=> WIP Comment command

src/main/java/com/bot/Bot.java, src/main/java/com/bot/Main.java, src/main/java/com/bot/caching/Cache.java, src/main/java/com/bot/caching/MarkovModelCache.java, src/main/java/com/bot/commands/GeneralCommand.java, src/main/java/com/bot/commands/MemeCommand.java, src/main/java/com/bot/commands/ModerationCommand.java, src/main/java/com/bot/commands/NSFWCommand.java, src/main/java/com/bot/commands/OwnerCommand.java, src/main/java/com/bot/commands/RedditCommand.java, src/main/java/com/bot/commands/VoiceCommand.java, src/main/java/com/bot/commands/general/ShardStatsCommand.java, src/main/java/com/bot/commands/voice/LoadGuildPlaylistCommand.java, src/main/java/com/bot/commands/voice/LoadMyPlaylistCommand.java, src/main/java/com/bot/commands/voice/StopCommand.java, src/main/java/com/bot/metrics/MetricsManager.java, src/main/java/com/bot/metrics/MetricsReporter.java, src/main/java/com/bot/models/InternalShard.java, src/main/java/com/bot/voice/VoiceSendHandler.java
Voice metrics were wrong
Get voice metrics off of the handlers. Make a thread to automatically report them. 
#53
=> Voice and some metrics rework, added metrics reporter thread

pom.xml, src/main/java/com/bot/Bot.java, src/main/java/com/bot/ShardingManager.java, src/main/java/com/bot/commands/voice/SearchCommand.java
No search command
Add it back
search
=> Add search command

src/main/java/com/bot/ShardingManager.java, src/main/java/com/bot/commands/general/StatsCommand.java
Need stats command to get back to pairity
Make a simple command to give a link to the dashboard
stats
=> add stats command

pom.xml, src/main/java/com/bot/ShardingManager.java, src/main/java/com/bot/commands/chan/R4cCommand.java, src/main/java/com/bot/commands/meme/CommentCommand.java, src/main/java/com/bot/utils/HttpUtils.java
=> 4chan commands

src/main/java/com/bot/Bot.java, src/main/java/com/bot/metrics/MetricsManager.java, src/main/java/com/bot/metrics/MetricsReporter.java, src/main/java/com/bot/models/InternalShard.java
=> Add more metrics and change when we leave voice automagically

src/main/java/com/bot/commands/reddit/NewPostCommand.java, src/main/java/com/bot/commands/reddit/RandomPostCommand.java, src/main/java/com/bot/commands/reddit/TopPostCommand.java, src/main/java/com/bot/utils/RedditHelper.java
reddit commands has shitty error handling
- fix it
=> Add better reddit error handling

src/main/java/com/bot/ShardingManager.java, src/main/java/com/bot/commands/general/ServerInfoCommand.java, src/main/java/com/bot/models/InternalShard.java, src/main/java/com/bot/preferences/GuildPreferencesManager.java
=> Add server info command

src/main/java/com/bot/Bot.java, src/main/java/com/bot/metrics/MetricsManager.java
=> added discord event metrics

src/main/java/com/bot/preferences/GuildPreferencesManager.java
=> Use cache when getting settings

src/main/java/com/bot/commands/meme/CommentCommand.java
=> Markov caching improvement

src/main/java/com/bot/Bot.java, src/main/java/com/bot/commands/GeneralCommand.java, src/main/java/com/bot/commands/MemeCommand.java, src/main/java/com/bot/commands/ModerationCommand.java, src/main/java/com/bot/commands/NSFWCommand.java, src/main/java/com/bot/commands/OwnerCommand.java, src/main/java/com/bot/commands/RedditCommand.java, src/main/java/com/bot/commands/VoiceCommand.java, src/main/java/com/bot/tasks/AddFreshGuildDeferredTask.java, src/main/java/com/bot/tasks/LeaveGuildDeferredTask.java, src/main/java/com/bot/utils/RedditHelper.java
Add deferred tasks for joining and leaving guilds. Run all commands asynchronously. Fix a reddit bug
=> More performance changes

src/main/java/com/bot/caching/R34Cache.java, src/main/java/com/bot/commands/nsfw/Rule34Command.java, src/main/java/com/bot/utils/CommandPermissions.java
=> Added new sources to commands

src/main/java/com/bot/utils/HttpUtils.java
missing one botlist stats posting
=> Add another botlist support

src/main/java/com/bot/ShardingManager.java, src/main/java/com/bot/commands/general/RollCommand.java, src/main/java/com/bot/commands/nsfw/Rule34Command.java, src/main/java/com/bot/commands/voice/DefaultVolumeCommand.java, src/main/java/com/bot/commands/voice/VolumeCommand.java
=> fix a couple bugs and use thread pools

src/main/java/com/bot/caching/Cache.java, src/main/java/com/bot/commands/GeneralCommand.java, src/main/java/com/bot/commands/MemeCommand.java, src/main/java/com/bot/commands/ModerationCommand.java, src/main/java/com/bot/commands/NSFWCommand.java, src/main/java/com/bot/commands/OwnerCommand.java, src/main/java/com/bot/commands/RedditCommand.java, src/main/java/com/bot/commands/VoiceCommand.java, src/main/java/com/bot/commands/general/RollCommand.java, src/main/java/com/bot/commands/meme/AsciiCommand.java, src/main/java/com/bot/commands/nsfw/Rule34Command.java, src/main/java/com/bot/commands/reddit/NewPostCommand.java, src/main/java/com/bot/commands/reddit/RandomPostCommand.java, src/main/java/com/bot/commands/reddit/ShitpostCommand.java, src/main/java/com/bot/commands/reddit/TopPostCommand.java, src/main/java/com/bot/commands/settings/GetSettingsCommand.java, src/main/java/com/bot/commands/settings/SetBaseRoleCommand.java, src/main/java/com/bot/commands/settings/SetModRoleCommand.java, src/main/java/com/bot/commands/settings/SetNSFWCommand.java, src/main/java/com/bot/commands/settings/SetVoiceRoleCommand.java, src/main/java/com/bot/commands/voice/LoadGuildPlaylistCommand.java, src/main/java/com/bot/commands/voice/LoadMyPlaylistCommand.java, src/main/java/com/bot/db/DataLoader.java, src/main/java/com/bot/preferences/GuildPreferencesManager.java
=> more metrics, move loggers to generic commands, add guild in prefs

src/main/java/com/bot/commands/reddit/NewPostCommand.java, src/main/java/com/bot/commands/reddit/RandomPostCommand.java, src/main/java/com/bot/commands/reddit/TopPostCommand.java, src/main/java/com/bot/utils/Logger.java, src/main/java/com/bot/utils/RedditHelper.java
- All reddit commands needed nsfw perms regardless of subreddit
- Logger channels would stale out, causing a cache thread crash
- Reddit 404s were not clear to user
=> A couple of bug fixes

src/main/java/com/bot/Bot.java, src/main/java/com/bot/commands/voice/PlayCommand.java, src/main/java/com/bot/commands/voice/SearchCommand.java, src/main/java/com/bot/db/DataLoader.java, src/main/java/com/bot/utils/FormattingUtils.java, src/main/java/com/bot/voice/LoadHandler.java, src/main/java/com/bot/voice/QueuedAudioTrack.java, src/main/java/com/bot/voice/VoiceSendHandler.java, src/main/test/java/utils/TestFormattingUtils.java, src/main/test/java/voice/TestQueuedAudioTrack.java, src/main/test/java/voice/TestVoiceSendHandler.java
New tracks were silent
- display an embed when a new track starts playing
=> Add embeds when new track

src/main/java/com/bot/commands/meme/CommentCommand.java, src/main/java/com/bot/models/MarkovModel.java
Markov comments could be too random
- Record double deep models as well and use them sometimes to get more coherent comments.
=> Markov tweaks

src/main/java/com/bot/Main.java, src/main/java/com/bot/ShardingManager.java, src/main/java/com/bot/commands/general/GamesCommand.java, src/main/java/com/bot/commands/general/PermissionsCommand.java, src/main/java/com/bot/commands/voice/NowPlayingCommand.java, src/main/java/com/bot/utils/FormattingUtils.java, src/main/java/com/bot/voice/QueuedAudioTrack.java, src/main/java/com/bot/voice/VoiceSendHandler.java, src/main/test/java/utils/FormattingUtilsTest.java
- #95  and a request for a now playing command
- Games
- nowplaying
=> Now playing games commands

src/main/java/com/bot/commands/voice/NowPlayingCommand.java, src/main/java/com/bot/commands/voice/VolumeCommand.java, src/main/java/com/bot/utils/FormattingUtils.java, src/main/java/com/bot/voice/VoiceSendHandler.java
- Now playing messages can be spammy
- Make them edit the last message if none have been posted since the last now playing.
-none
- volume, now playing
=> Now playing will edit old messages

src/main/java/com/bot/Bot.java, src/main/java/com/bot/tasks/AddFreshGuildDeferredTask.java, src/main/java/com/bot/utils/ConstantStrings.java, src/main/java/com/bot/utils/GuildUtils.java
- Vinny is quiet when joining new servers
- Find the appropriate channel and send a message
=> Send welcome message when joining a new server.

docs/Commands.md, src/main/java/com/bot/ShardingManager.java, src/main/java/com/bot/commands/meme/P90Command.java, src/main/java/com/bot/utils/Config.java, src/main/java/com/bot/utils/HttpUtils.java
- WE NEED MORE MEMES
- make it
- p90 command
=> add P90 command

src/main/java/com/bot/utils/Config.java, src/main/java/com/bot/utils/HttpUtils.java
=> Add botlist space posting

src/main/java/com/bot/Bot.java, src/main/java/com/bot/Main.java, src/main/java/com/bot/caching/TextChannelCache.java, src/main/java/com/bot/commands/general/PixivCommand.java, src/main/java/com/bot/commands/meme/P90Command.java, src/main/java/com/bot/commands/reddit/NewPostCommand.java, src/main/java/com/bot/commands/reddit/RandomPostCommand.java, src/main/java/com/bot/commands/reddit/TopPostCommand.java, src/main/java/com/bot/db/AliasDAO.java, src/main/java/com/bot/db/ChannelDAO.java, src/main/java/com/bot/db/GuildDAO.java, src/main/java/com/bot/metrics/MetricsManager.java, src/main/java/com/bot/models/Alias.kt, src/main/java/com/bot/models/InternalGuild.java, src/main/java/com/bot/models/InternalTextChannel.kt, src/main/java/com/bot/utils/CommandPermissions.java, src/main/java/com/bot/utils/Config.java, src/main/resources/db/migration/V5__add_command_aliases.sql, src/main/test/java/db/AliasIT.java, src/main/test/java/db/ChannelIT.java, src/main/test/java/db/GuildIT.java
We need a way to represent aliases for commands
add a db dao/dal layer to accomplish this
=> Add aliasDAO, and text channel cache

src/main/java/com/bot/db/ConnectionPool.java
=> Add dao for alias support

src/main/java/com/bot/Bot.java, src/main/java/com/bot/Main.java, src/main/java/com/bot/caching/TextChannelCache.java, src/main/java/com/bot/commands/general/PixivCommand.java, src/main/java/com/bot/commands/meme/P90Command.java, src/main/java/com/bot/commands/reddit/NewPostCommand.java, src/main/java/com/bot/commands/reddit/RandomPostCommand.java, src/main/java/com/bot/commands/reddit/TopPostCommand.java, src/main/java/com/bot/db/AliasDAO.java, src/main/java/com/bot/db/ChannelDAO.java, src/main/java/com/bot/db/GuildDAO.java, src/main/java/com/bot/metrics/MetricsManager.java, src/main/java/com/bot/models/Alias.kt, src/main/java/com/bot/models/InternalGuild.java, src/main/java/com/bot/models/InternalTextChannel.kt, src/main/java/com/bot/utils/CommandPermissions.java, src/main/java/com/bot/utils/Config.java, src/main/resources/db/migration/V5__add_command_aliases.sql, src/main/test/java/db/AliasIT.java, src/main/test/java/db/ChannelIT.java, src/main/test/java/db/GuildIT.java
Reverts JessWalters/Vinny-Redux#109
=> Revert "Revert "Add aliasDAO, and text channel cache""

src/main/java/com/bot/ShardingManager.java, src/main/java/com/bot/commands/general/SayCommand.java, src/main/java/com/bot/utils/FormattingUtils.java
=> add say command

docs/Aliases.md, docs/Commands.md, pom.xml, src/main/java/com/bot/Bot.java, src/main/java/com/bot/ShardingManager.java, src/main/java/com/bot/commands/alias/AddGuildAliasCommand.java, src/main/java/com/bot/commands/alias/AliasesCommand.java, src/main/java/com/bot/commands/alias/RemoveAliasCommand.java, src/main/java/com/bot/commands/alias/RemoveGuildAliasCommand.java, src/main/java/com/bot/db/GuildDAO.java, src/main/java/com/bot/metrics/MetricsManager.java, src/main/java/com/bot/models/InternalGuild.java, src/main/java/com/bot/models/InternalUser.kt, src/main/java/com/bot/preferences/GuildPreferencesProvider.java, src/main/java/com/bot/utils/AliasUtils.java, src/main/java/com/bot/utils/ConstantStrings.java, src/main/java/com/bot/utils/Logger.java
Adding guild aliases, allowing users to define their own command triggers in their guild
=> Guild aliases

docs/Commands.md, src/main/java/com/bot/ShardingManager.java, src/main/java/com/bot/commands/meme/ClapCommand.java, src/main/java/com/bot/commands/meme/CopyPastaCommand.java, src/main/java/com/bot/utils/FormattingUtils.java, src/main/java/com/bot/utils/GuildUtils.java, src/main/java/com/bot/utils/RedditHelper.java
=> add copypasta and clap commands

src/main/java/com/bot/Main.java, src/main/java/com/bot/ShardingManager.java, src/main/java/com/bot/commands/owner/UpdateGuildCountCommand.java, src/main/java/com/bot/db/DataLoader.java, src/main/java/com/bot/db/GuildDAO.java, src/main/java/com/bot/db/mappers/GuildMapper.java, src/main/java/com/bot/models/InternalGuild.java, src/main/java/com/bot/tasks/LeaveGuildDeferredTask.kt, src/main/java/com/bot/utils/Config.java, src/main/java/com/bot/utils/ConstantStrings.java, src/main/java/com/bot/utils/HttpUtils.java, src/main/resources/db/migration/V6__add_guild_active_column.sql, src/main/test/java/db/AliasIT.java, src/main/test/java/db/ChannelIT.java, src/main/test/java/db/GuildIT.java, src/main/test/java/db/PlaylistIT.java
Vinny big, need more cpu
Support delegating shards to more than one machine
=> Support multiple machines

src/main/java/com/bot/Bot.java, src/main/java/com/bot/commands/voice/PlayCommand.java, src/main/java/com/bot/commands/voice/SearchCommand.java, src/main/java/com/bot/exceptions/MaxQueueSizeException.kt, src/main/java/com/bot/voice/LoadHandler.java, src/main/java/com/bot/voice/VoiceSendHandler.java
- Youtube banning us
- limit the number of tracks to load, most are forgotten when a stream is stop, lets stop wasting those YT calls
=> voice mitigations

pom.xml, src/main/java/com/bot/commands/voice/PlayCommand.java, src/main/java/com/bot/commands/voice/SearchCommand.java, src/main/java/com/bot/voice/VoiceSendHandler.java
- update lavaplayer and better ux around lockdown voice atm
=> pbjtest3 and better ux around voice lockdown

Dockerfile, pom.xml, src/main/java/com/bot/ShardingManager.java, src/main/java/com/bot/utils/Config.java, src/main/java/com/bot/utils/Logger.java
-Logging to discord across multiple hosts sucks
- Utilize dislog to aleviate this pain
=> use dislog for logging to channels

.gitignore, docs/Commands.md, src/main/java/com/bot/ShardingManager.java, src/main/java/com/bot/commands/voice/LockVolumeCommand.java, src/main/java/com/bot/commands/voice/VolumeCommand.java, src/main/java/com/bot/voice/VoiceSendHandler.java
- With volume so accessible anyone can edit it
- Add the ability to lock it
- lock volume command
- volume
=> add volume lock

src/main/java/com/bot/commands/voice/PlayCommand.java, src/main/java/com/bot/voice/VoiceSendHandler.java
=> up max queue size, remove playlist lockl

pom.xml, src/main/java/com/bot/Bot.java, src/main/java/com/bot/utils/Config.java, src/main/java/com/bot/utils/LavaPlayerUtils.java
=> Ip rotation

src/main/java/com/bot/utils/HttpUtils.java
=> Stop logging 500 errors on external service as error

src/main/java/com/bot/ShardingManager.java, src/main/java/com/bot/commands/owner/RebootAnnounceCommand.java, src/main/java/com/bot/models/InternalShard.kt, src/main/java/com/bot/utils/ConstantStrings.java, src/main/java/com/bot/utils/HttpUtils.java, src/main/java/com/bot/voice/VoiceSendHandler.java
=> add reboot warnings, fix del api

pom.xml, src/main/java/com/bot/Bot.java, src/main/java/com/bot/utils/LavaPlayerUtils.java
=> Revert "Lavaplayer bump"

src/main/java/com/bot/db/ScheduledCommandDAO.java, src/main/java/com/bot/tasks/RunScheduledCommandsDefferedTask.kt, src/main/resources/db/migration/V9__add_scheduled_command_run_table.sql
=> add db table to track all runs of scheduled commands

pom.xml, src/main/java/com/bot/Bot.java, src/main/java/com/bot/ShardingManager.java, src/main/java/com/bot/commands/owner/SwitchDefaultSearchCommand.java, src/main/java/com/bot/commands/voice/PlayCommand.java, src/main/java/com/bot/commands/voice/SearchCommand.java, src/main/java/com/bot/metrics/MetricsManager.java, src/main/java/com/bot/utils/Config.java, src/main/java/com/bot/utils/LavaPlayerUtils.java
Lavaplayer is out of date
Implement newer lavaplayer and sc search switch
=> Lavaplayer bump

src/main/java/com/bot/utils/HttpUtils.java, src/main/java/com/bot/utils/LavaPlayerUtils.java, src/main/java/com/bot/voice/MyRotatingIpPlanner.java
Lp ip rotation is broke
Implement a custom solution to fix it
=> Implement custom rotater while waiting for lp pr

docs/Commands.md, src/main/java/com/bot/ShardingManager.java, src/main/java/com/bot/caching/GuildCache.java, src/main/java/com/bot/caching/R34Cache.java, src/main/java/com/bot/caching/SubredditCache.java, src/main/java/com/bot/commands/BaseCommand.java, src/main/java/com/bot/commands/owner/FUserCommand.java, src/main/java/com/bot/commands/owner/ForceSendMessage.java, src/main/java/com/bot/commands/owner/InChannelCommand.java, src/main/java/com/bot/commands/owner/InGuildCommand.java, src/main/java/com/bot/commands/owner/ShardCommand.java, src/main/java/com/bot/commands/voice/RemoveTrackCommand.java, src/main/java/com/bot/commands/voice/RepeatCommand.java, src/main/java/com/bot/utils/CommandPermissions.java, src/main/java/com/bot/utils/Config.java, src/main/java/com/bot/voice/VoiceSendHandler.java
=> add patches to some bugs, more owner debug commands

src/main/java/com/bot/utils/CommandPermissions.java
=> Revert "hotfix"

docs/Commands.md, src/main/java/com/bot/ShardingManager.java, src/main/java/com/bot/caching/GuildCache.java, src/main/java/com/bot/caching/R34Cache.java, src/main/java/com/bot/caching/SubredditCache.java, src/main/java/com/bot/commands/BaseCommand.java, src/main/java/com/bot/commands/owner/FUserCommand.java, src/main/java/com/bot/commands/owner/ForceSendMessage.java, src/main/java/com/bot/commands/owner/InChannelCommand.java, src/main/java/com/bot/commands/owner/InGuildCommand.java, src/main/java/com/bot/commands/owner/ShardCommand.java, src/main/java/com/bot/commands/voice/RemoveTrackCommand.java, src/main/java/com/bot/commands/voice/RepeatCommand.java, src/main/java/com/bot/utils/CommandPermissions.java, src/main/java/com/bot/voice/VoiceSendHandler.java
=> Revert "Revert "add patches to some bugs, more owner debug commands""

src/main/java/com/bot/ShardingManager.java, src/main/java/com/bot/utils/FormattingUtils.java
Help message was not long enough causing truncation
Allow more max messages for command event replies
=> fix help message

src/main/java/com/bot/commands/moderation/PurgeCommand.kt, src/main/java/com/bot/commands/scheduled/ScheduleCommand.java, src/main/java/com/bot/db/ConnectionPool.java, src/main/java/com/bot/db/ScheduledCommandDAO.java, src/main/java/com/bot/tasks/RunScheduledCommandsDefferedTask.kt, src/main/java/com/bot/voice/VoiceSendHandler.java
=> scheduled-command-batching of last run updates

src/main/java/com/bot/commands/moderation/PurgeCommand.kt, src/main/java/com/bot/commands/scheduled/ScheduleCommand.java, src/main/java/com/bot/db/ConnectionPool.java, src/main/java/com/bot/db/ScheduledCommandDAO.java, src/main/java/com/bot/tasks/RunScheduledCommandsDefferedTask.kt, src/main/java/com/bot/voice/VoiceSendHandler.java
=> Revert "scheduled-command-batching of last run updates"

docs/Commands.md, pom.xml, src/main/java/com/bot/ShardingManager.java, src/main/java/com/bot/commands/meme/KickRouletteCommand.java, src/main/java/com/bot/commands/meme/MemeKickCommand.java, src/main/java/com/bot/commands/reddit/RandomPostCommand.java, src/main/java/com/bot/commands/scheduled/ScheduleCommand.java, src/main/java/com/bot/consumers/ReRoleConsumer.java, src/main/java/com/bot/metrics/MetricsManager.java, src/main/java/com/bot/utils/ConstantStrings.java
=> Meme kicks

docs/Commands.md, pom.xml, src/main/java/com/bot/ShardingManager.java, src/main/java/com/bot/commands/BaseCommand.java, src/main/java/com/bot/commands/GeneralCommand.kt, src/main/java/com/bot/commands/MemeCommand.kt, src/main/java/com/bot/commands/ModerationCommand.kt, src/main/java/com/bot/commands/NSFWCommand.kt, src/main/java/com/bot/commands/OwnerCommand.kt, src/main/java/com/bot/commands/RedditCommand.kt, src/main/java/com/bot/commands/VoiceCommand.kt, src/main/java/com/bot/commands/meme/SauceCommand.kt, src/main/java/com/bot/commands/scheduled/ScheduleCommand.java, src/main/java/com/bot/utils/Config.java, src/main/java/com/bot/utils/FormattingUtils.java, src/main/java/com/bot/utils/SauceUtils.java
=> Sauce command

pom.xml, src/main/java/com/bot/Bot.java, src/main/java/com/bot/caching/Cache.java, src/main/java/com/bot/caching/GuildCache.java, src/main/java/com/bot/caching/MarkovModelCache.java, src/main/java/com/bot/caching/R34Cache.java, src/main/java/com/bot/caching/SubredditCache.java, src/main/java/com/bot/caching/TextChannelCache.java, src/main/java/com/bot/caching/WebhookClientCache.java, src/main/java/com/bot/commands/general/HelpCommand.kt, src/main/java/com/bot/commands/general/SayCommand.kt, src/main/java/com/bot/commands/nsfw/R4cCommand.java, src/main/java/com/bot/commands/nsfw/Rule34Command.java, src/main/java/com/bot/commands/reddit/NewPostCommand.java, src/main/java/com/bot/commands/reddit/RandomPostCommand.java, src/main/java/com/bot/commands/reddit/TopPostCommand.java, src/main/java/com/bot/commands/scheduled/ScheduleCommand.java, src/main/java/com/bot/exceptions/ScheduledCommandFailedException.kt, src/main/java/com/bot/metrics/MetricsManager.java, src/main/java/com/bot/utils/ConstantStrings.java, src/main/java/com/bot/utils/HttpUtils.java, src/main/java/com/bot/utils/RedditHelper.java, src/main/java/com/bot/utils/ScheduledCommandUtils.java
- Due to high traffic and hitting global rate limits some commands are taking forever to get sent
- Start sending some commands through webhooks when they are scheduled.
- rr, nr, tr, say, r4c, r34
=> port scheduled commands to webhooks

pom.xml, src/main/java/com/bot/Main.java, src/main/java/com/bot/commands/rss/SubscribeTwitterCommand.java, src/main/java/com/bot/db/RssDAO.java, src/main/java/com/bot/messaging/RssSubscriber.kt, src/main/java/com/bot/metrics/MetricsManager.java, src/main/java/com/bot/metrics/MetricsReporter.java, src/main/java/com/bot/models/RSSProvider.kt, src/main/java/com/bot/models/RssUpdate.kt, src/main/java/com/bot/utils/Config.java, src/main/java/com/bot/utils/RssUtils.kt, src/main/java/com/bot/utils/ScheduledCommandUtils.java, src/main/resources/db/migration/V12__Add_Rss_tables.sql
=> Add nats handlers to receive rss events

src/main/java/com/bot/ShardingManager.java, src/main/java/com/bot/commands/rss/CreateSubscriptionCommand.kt, src/main/java/com/bot/commands/rss/RemoveSubscriptionCommand.java, src/main/java/com/bot/commands/rss/SubscribeChanCommand.java, src/main/java/com/bot/commands/rss/SubscribeRedditCommand.java, src/main/java/com/bot/commands/rss/SubscribeTwitterCommand.java, src/main/java/com/bot/commands/rss/SubscriptionsCommand.java, src/main/java/com/bot/commands/scheduled/UnscheduleCommand.java, src/main/java/com/bot/db/RssDAO.java, src/main/java/com/bot/db/mappers/RssChannelSubscriptionMapper.java, src/main/java/com/bot/db/mappers/RssSubscriptionMapper.java, src/main/java/com/bot/exceptions/SubscriptionAlreadyExistsException.kt, src/main/java/com/bot/models/RSSProvider.kt, src/main/java/com/bot/models/RssChannelSubscription.kt, src/main/java/com/bot/models/RssSubscription.kt, src/main/java/com/bot/utils/ChanUtils.kt, src/main/java/com/bot/utils/ConstantStrings.java, src/main/java/com/bot/utils/RedditHelper.java, src/main/java/com/bot/utils/RssUtils.kt, src/main/resources/db/migration/V13__Add_rss_comp_key.sql, src/main/resources/db/migration/V14__Add_NSFW_subscription_flag.sql, src/main/resources/db/migration/V15__add_rss_channel_comp_key.sql
=> Add commands for subscriptions

docs/Commands.md, docs/Subscriptions.md, src/main/java/com/bot/ShardingManager.java, src/main/java/com/bot/commands/rss/SubscribeTwitchCommand.java, src/main/java/com/bot/commands/rss/SubscribeYoutubeCommand.java, src/main/java/com/bot/exceptions/InvalidInputException.kt, src/main/java/com/bot/exceptions/NoSuchResourceException.kt, src/main/java/com/bot/exceptions/TwitchUserNotFoundException.kt, src/main/java/com/bot/utils/ConstantStrings.kt, src/main/java/com/bot/utils/HttpUtils.java, src/main/java/com/bot/utils/RssUtils.kt
Add yt subscription command to allow yt channel subs.
Also allow twitch url in the subscribe command
=> Yt sub command

src/main/java/com/bot/commands/general/HelpCommand.kt, src/main/java/com/bot/utils/HttpUtils.java
Put a time limit on help frequency
Fix an issue finding the YT ids of some channels
=> help limit, yt subscribe fix

docs/Commands.md, pom.xml, src/main/java/com/bot/ShardingManager.java, src/main/java/com/bot/caching/E621Cache.java, src/main/java/com/bot/commands/BaseCommand.java, src/main/java/com/bot/commands/nsfw/E621Command.java, src/main/java/com/bot/commands/rss/SubscribeRedditCommand.java, src/main/java/com/bot/utils/HttpUtils.java, src/main/java/com/bot/utils/RssUtils.kt
Do to user request, add an e621 command. Pure degeneracy, which I guess fits the theme of the bot. What am I doing with my life?
=> e621 command first pass, revert dd client version

src/main/java/com/bot/Bot.java, src/main/java/com/bot/commands/nsfw/Rule34Command.java, src/main/java/com/bot/commands/rss/SubscribeChanCommand.java, src/main/java/com/bot/utils/ConstantStrings.kt
=> add paheal as r34 source, streamline chan

src/main/java/com/bot/ShardingManager.java, src/main/java/com/bot/commands/BaseCommand.java
=> rip intent

src/main/java/com/bot/ShardingManager.java, src/main/java/com/bot/commands/general/InviteCommand.kt
=> add members intent back

.travis.settings.xml, src/main/java/com/bot/commands/RedditCommand.kt
=> remove-cooldown on reddit commands

src/main/java/com/bot/Bot.java, src/main/java/com/bot/commands/meme/P90Command.kt, src/main/java/com/bot/commands/nsfw/R4cCommand.java, src/main/java/com/bot/commands/nsfw/Rule34Command.java, src/main/java/com/bot/db/ConnectionPool.java
=> remove cooldowns

src/main/java/com/bot/Bot.java
=> Remove accidental debug log

src/main/java/com/bot/Bot.java, src/main/java/com/bot/db/GuildDAO.java, src/main/java/com/bot/utils/CommandPermissions.java
=> optimize usage of getGuilds

docs/Commands.md, src/main/java/com/bot/utils/Config.java, src/main/java/com/bot/voice/VoiceSendHandler.java
=> remove some references

pom.xml, src/main/java/com/bot/metrics/MetricsManager.kt
Bump some old deps to newer versions
=> bump some deps in pom and update breaking change with statd

docs/Commands.md, src/main/java/com/bot/commands/voice/RepeatCommand.kt
Repeat command doesn't work as it is explained in the documentation
Fix the repeat command documentation and arguments description
- **repeat** - Changed the arguments description and made [one] check to be case-insensitive
No
No
No
=> fix: repeat description and ignoreCase

docs/Commands.md, src/main/java/com/bot/Bot.java, src/main/java/com/bot/ShardingManager.java, src/main/java/com/bot/commands/general/PremiumServerCommand.kt, src/main/java/com/bot/commands/voice/AutoplayCommand.kt, src/main/java/com/bot/db/GuildDAO.java, src/main/java/com/bot/db/MembershipDAO.java, src/main/java/com/bot/db/mappers/GuildMembershipMapper.java, src/main/java/com/bot/metrics/MetricsManager.kt, src/main/java/com/bot/models/InternalGuildMembership.kt, src/main/java/com/bot/models/UsageLevel.kt, src/main/java/com/bot/tasks/MetricsReporter.kt, src/main/java/com/bot/utils/FormattingUtils.java, src/main/java/com/bot/utils/VinnyConfig.kt, src/main/java/com/bot/voice/AutoplayClient.kt, src/main/java/com/bot/voice/AutoplayLoadHandler.kt, src/main/java/com/bot/voice/GuildVoiceConnection.kt, src/main/java/com/bot/voice/LLLoadHandler.kt, src/main/java/com/bot/voice/QueuedAudioTrack.kt, src/main/java/com/bot/voice/SearchLLLoadHandler.kt, src/main/resources/db/migration/V23__add_server_premium.sql, src/main/test/java/db/GuildIT.java, src/main/test/java/db/PlaylistIT.java
=> Add autoplay
